Repository Educado-App/educado-frontend, pull requests merged in 2024-10, with the labels that each got.

#141 feature/confirmation-dialog
  app/__tests__/src/pages/__snapshots__/Login.test.js.snap
  app/src/components/Application/Motivation.tsx
  app/src/components/GenericModalComponent.tsx
  app/src/components/styles/GenericModalComponent.css
  app/src/pages/Application.tsx
  app/src/pages/Login.tsx
  app/src/pages/Signup.tsx
Labels: enhancement

#139 Upload image to course + show image on course overview
  app/src/components/Courses/CourseComponent.tsx
  app/src/components/Courses/CourseListCard.tsx
  app/src/components/Dropzone/Dropzone.tsx
  app/src/services/course.services.ts
  app/src/services/storage.services.ts
Labels: bug, documentation, enhancement

#152 Deadlocked course navigation
  app/src/components/Checklist.tsx
  app/src/components/Courses/CourseComponent.tsx
  app/src/components/SectionCreation.tsx
  app/src/pages/CourseManager.tsx
Labels: bug, enhancement, pbi

#169 Extra academic and experience forms on /application and /profile
  app/__tests__/src/pages/__snapshots__/Login.test.js.snap
  app/__tests__/src/pages/__snapshots__/Signup.test.js.snap
  app/__tests__/src/pages/__snapshots__/Welcome.test.js.snap
  app/src/components/Application/AcademicExperience.tsx
  app/src/components/Application/Motivation.tsx
  app/src/components/Application/ProfessionalExperience.tsx
  app/src/components/GenericModalComponent.tsx
  app/src/components/Layout.tsx
  app/src/components/ProfileForms/AcademicExperience.tsx
  app/src/components/ProfileForms/PersonalInformation.tsx
  app/src/components/ProfileForms/ProfessionalExperience.tsx
  app/src/components/navbar/MiniNavbar.tsx
  app/src/components/navbar/Navbar.tsx
  app/src/components/profile/PopUpDelete.tsx
  app/src/helpers/formStates.ts
  app/src/interfaces/Application.ts
  app/src/interfaces/Profile.ts
  app/src/pages/Application.tsx
  app/src/pages/Login.tsx
  app/src/pages/Profile.tsx
  app/src/pages/Signup.tsx
  app/src/pages/Welcome.tsx
  app/src/services/auth.services.ts
  app/src/services/profile.services.ts
  app/src/utilities/dynamicForms.ts
  app/src/utilities/useProfileValidation.ts
Labels: enhancement
